### ISSUE TITLE
Why isn't CompressedTracks exported in acl.js?

### ISSUE THREAD

**Issue by reimund** [nfrechette/acl-js#24]
Thank you for a great library but I'm struggling with decompressing my data.

I need the CompressedTracks class to have something to bind the decoder to but it's not exported in acl.js.
Or am I missing something?

**Comment by nfrechette** [comment]
Thank you for reporting this. This indeed looks like an omission as the CompressedTracks should be exported but isn't at the moment.

If your raw buffer is loaded from a resource, you'll need it to decompress. I'll make a patch in the next day or two and push it to npm.

**Comment by reimund** [comment]
Awesome, thanks!

**Comment by nfrechette** [comment]
Will be fixed in v0.1.1 I'll be publishing shortly. Thanks for reporting this!
